### ISSUE TITLE
[BUG] Upgrade php8.2 broke piwigo

### ISSUE THREAD

**Issue by ste69008** [linuxserver/docker-piwigo#63] opened 2023-06-01 19:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Since i update my docker image to 13.7.0, my piwigo website is borken with a lot of this messages : 

Deprecated
: Creation of dynamic property Smarty_Internal_Extension_Handler::$unregisterFilter is deprecated in
/config/www/gallery/include/smarty/libs/sysplugins/smarty_internal_extension_handler.php
on line
182

Deprecated
: Creation of dynamic property CssAtMediaStartToken::$MediaTypes is deprecated in
/config/www/gallery/include/cssmin.class.php
on line
34

### Expected Behavior

I think it's the same problem here : https://piwigo.org/forum/viewtopic.php?id=32728

### Steps To Reproduce

Just open login webpage

### Environment

```markdown
- OS: Synology
- How docker service was installed: package
```

### CPU architecture

x86-64

### Docker creation

```bash
basic docker run
```

### Container logs

```bash
nothings in logs
```

**Comment by jdespraz** [comment] 2023-06-01 20:40
I can confirm this bug. I was also able to reproduce it on a fresh install of piwigo from the latest image on dockerhub.
It seems that a fix has been implemented in the piwigo source code, see e.g.
https://github.com/Piwigo/Piwigo/blob/ebcdb343058df6bc942d695e40cb01ef5867a713/include/smarty/libs/sysplugins/smarty_internal_extension_handler.php#L39 

Strangely enough, I wasn't able to remove the warnings by editing the variables in the PHP config file (`config/www/local/config/config.inc.php`) and setting the variable
`$conf['show_php_errors_on_frontend'] = false;`
or
`$conf['show_php_errors'] = '';`

The only thing that worked was to manually edit the source files generating the deprecation warnings and adding the 
`#[\AllowDynamicProperties]` line before the class declarations.

**Comment by tom666-debug** [comment] 2023-06-02 05:20
I am facing the same issue here right after the update to version 13.7.0-ls214. After a fallback to version 13.7.0-ls213 everything is working as expected again.

**Comment by pvillaverde** [comment] 2023-06-03 09:23
Same here. All full with deprecation warnings and 502 errors when trying to access the admin section. Rolled back to the 13.7.0-ls213 as suggested by @tom666-debug and it's working.

**Closed** 2023-06-03 14:24 UTC

**Comment by michauk** [comment] 2023-11-07 16:39
Hi there,
Personally, I waited before upgrading Debian to release 12 because of PHP 8.2 which becomes the default, so the various PHP app I'm hosting wouldn't break all at the same time.
Only piwigo got broken.
I'm don't want to downgrade and waste time. The right solution will be when piwigo will be fully-compatible.
Right now, to do a quick workaround, I just added the #[AllowDynamicProperties] directive before each class in all piwigo's PHP files with one quick command. I'm just writing this if anyone needs that kind of solution, too.
`for i in \`find /path/to/piwigo -type f -name "*php"\`
do
sed -i -e '/^class /i #[AllowDynamicProperties]' $i
done`

I hope this will help some people.

I did not understand the solution in issue #64 mentionned above.
Btw, I'm not using a docker-based piwigo, but the same problem applies.
